In [33]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/sakshisatre/titanic-dataset/The Titanic dataset.csv
/kaggle/input/datasets/sakshisatre/titanic-dataset/Titanic Dataset.csv

In [34]:
from sklearn.model_selection import  train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2

In [35]:
df = pd.read_csv("/kaggle/input/datasets/sakshisatre/titanic-dataset/Titanic Dataset.csv")

In [36]:
df.sample(5)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
846,3,0,"Hampe, Mr. Leon",male,20.0,0,0,345769,9.500,NaN,S,NaN,NaN,NaN
461,2,0,"Jarvis, Mr. John Denzil",male,47.0,0,0,237565,15.000,NaN,S,NaN,NaN,"North Evington, England"
396,2,1,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.000,NaN,S,NaN,NaN,Southampton
10,1,0,"Astor, Col. John Jacob",male,47.0,1,0,PC 17757,227.525,C62 C64,C,NaN,124.0,"New York, NY"
712,3,0,"Celotti, Mr. Francesco",male,24.0,0,0,343275,8.050,NaN,S,NaN,NaN,London

In [37]:
df.drop(columns=['name','ticket','cabin','boat','body','home.dest'],inplace=True)

In [38]:
df

      pclass  survived     sex    age  sibsp  parch      fare embarked
0          1         1  female  29.00      0      0  211.3375        S
1          1         1    male   0.92      1      2  151.5500        S
2          1         0  female   2.00      1      2  151.5500        S
3          1         0    male  30.00      1      2  151.5500        S
4          1         0  female  25.00      1      2  151.5500        S
...      ...       ...     ...    ...    ...    ...       ...      ...
1304       3         0  female  14.50      1      0   14.4542        C
1305       3         0  female    NaN      1      0   14.4542        C
1306       3         0    male  26.50      0      0    7.2250        C
1307       3         0    male  27.00      0      0    7.2250        C
1308       3         0    male  29.00      0      0    7.8750        S

[1309 rows x 8 columns]

In [39]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['survived']),
                                                 df['survived'],
                                                 test_size=0.2,
                                                random_state=42)

In [40]:
X_train

      pclass     sex   age  sibsp  parch      fare embarked
772        3    male  17.0      0      0    7.8958        S
543        2    male  36.0      0      0   10.5000        S
289        1  female  18.0      0      2   79.6500        S
10         1    male  47.0      1      0  227.5250        C
147        1    male   NaN      0      0   42.4000        S
...      ...     ...   ...    ...    ...       ...      ...
1095       3  female   NaN      0      0    7.6292        Q
1130       3  female  18.0      0      0    7.7750        S
1294       3    male  28.5      0      0   16.1000        S
860        3  female  26.0      0      0    7.9250        S
1126       3  female  28.0      0      0    7.8958        S

[1047 rows x 7 columns]

In [41]:
y_train.sample(4)

238     1
838     0
786     0
1019    0
Name: survived, dtype: int64

In [42]:
# imputation transformer
trf1 = ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('impute_embarked',SimpleImputer(strategy='most_frequent'),[6])
],remainder='passthrough')

In [44]:
# one hot encoding
trf2 = ColumnTransformer([
    ('ohe_sex_embarked',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),[1,6])
],remainder='passthrough')

In [45]:
# Scaling
trf3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])

In [46]:
trf4 = SelectKBest(score_func=chi2,k=8)

In [47]:
# train the model
trf5 = DecisionTreeClassifier()

# Create Pipeline

In [49]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])

# Pipeline Vs make_pipeline
Pipeline requires naming of steps, make_pipeline does not.

(Same applies to ColumnTransformer vs make_column_transformer)

In [ ]:
# Alternate Syntax
#pipe = make_pipeline(trf1,trf2,trf3,trf4,trf5)

In [50]:
# train
pipe.fit(X_train,y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('trf3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('trf4',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x79d3203c0a40>)),
                ('trf5', DecisionTreeClassifier())])

In [52]:
pipe.named_steps['trf1']

ColumnTransformer(remainder='passthrough',
                  transformers=[('impute_age', SimpleImputer(), [2]),
                                ('impute_embarked',
                                 SimpleImputer(strategy='most_frequent'),
                                 [6])])

In [53]:
pipe.named_steps['trf1'].transformers_

[('impute_age', SimpleImputer(), [2]),
 ('impute_embarked', SimpleImputer(strategy='most_frequent'), [6]),
 ('remainder',
  FunctionTransformer(accept_sparse=True, check_inverse=False,
                      feature_names_out='one-to-one'),
  [0, 1, 3, 4, 5])]

In [54]:
# Predict
y_pred = pipe.predict(X_test)

In [55]:
y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1])

In [56]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6030534351145038

# Exporting the Pipeline

In [57]:
# export 
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))