In [35]:
import pandas as pd

# WORKING WITH JSON

In [36]:
df=pd.read_json('train.json',typ="series")
df

0        {'id': 10259, 'cuisine': 'greek', 'ingredients...
1        {'id': 25693, 'cuisine': 'southern_us', 'ingre...
2        {'id': 20130, 'cuisine': 'filipino', 'ingredie...
3        {'id': 22213, 'cuisine': 'indian', 'ingredient...
4        {'id': 13162, 'cuisine': 'indian', 'ingredient...
                               ...
39769    {'id': 29109, 'cuisine': 'irish', 'ingredients...
39770    {'id': 11462, 'cuisine': 'italian', 'ingredien...
39771    {'id': 2238, 'cuisine': 'irish', 'ingredients'...
39772    {'id': 41882, 'cuisine': 'chinese', 'ingredien...
39773    {'id': 2362, 'cuisine': 'mexican', 'ingredient...
Length: 39774, dtype: object

In [37]:
#df=pd.read_json('train.json',lines =True)

In [38]:
pd.read_json("train.json").head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

# WORKING WITH SQL

In [39]:
# !pip install mysql.connector

In [40]:
import mysql.connector

In [41]:
conn = mysql.connector.connect(host = 'localhost',user='root',password='12344321',database='bank')

In [49]:
dc=pd.read_sql_query("select * from customer ",conn)
dc

C:\Users\user\AppData\Local\Temp\ipykernel_5732\2398098019.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dc=pd.read_sql_query("select * from customer ",conn)

  customer_id customer_name
0          C1        Faizan
1          C2         Ashir
2          C3        Imraan
3          C4          Anas
4          C5         Tuaha

In [50]:
dc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      object
 1   customer_name  5 non-null      object
dtypes: object(2)
memory usage: 212.0+ bytes

#
# API And working:

## API = Application programming interface 
Api make contact between two softwares. In simple way you can say that api is data pipelines 
which reach information from one point to other point example is train seat booking explained in notes

In [52]:
import pandas as pd
import requests

In [54]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=df8a1de3b78fcea127629facad805793&language=en-US&page=1')

In [63]:
df = pd.DataFrame(response.json()['results'])[['id','title','vote_count','release_date','popularity']]
df.head()

    id                     title  vote_count release_date  popularity
0  278  The Shawshank Redemption       29794   1994-09-23     43.3592
1  238             The Godfather       22497   1972-03-14     40.3175
2  240     The Godfather Part II       13614   1974-12-20     20.0106
3  424          Schindler's List       17140   1993-12-15     15.4284
4  389              12 Angry Men        9763   1957-04-10     13.1707

In [65]:
df = pd.DataFrame()

In [66]:
df

Empty DataFrame
Columns: []
Index: []

In [74]:
# for i in range (1,534):
df_list = []

for i in range(1, 13):  # There are total of 534 pages but it tooks too much time so for convienience i had just run 13 pages
    response = requests.get(
        'https://api.themoviedb.org/3/movie/top_rated?api_key=df8a1de3b78fcea127629facad805793&language=en-US&page={}'.format(i)
    )
    temp_df = pd.DataFrame(response.json()['results'])[
        ['id', 'title', 'vote_count', 'release_date', 'popularity']
    ]
    df_list.append(temp_df)
df = pd.concat(df_list, ignore_index=True)
    # response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=df8a1de3b78fcea127629facad805793&language=en-US&page={}'.format(i))
    # temp_df = pd.DataFrame(response.json()['results'])[['id','title','vote_count','release_date','popularity']]
    # df = df.append(temp_df,ignore_index = True)
df

,id,title,vote_count,release_date,popularity
0,278,The Shawshank Redemption,29794,1994-09-23,43.3592
1,238,The Godfather,22497,1972-03-14,40.3175
2,240,The Godfather Part II,13614,1974-12-20,20.0106
3,424,Schindler's List,17140,1993-12-15,15.4284
4,389,12 Angry Men,9763,1957-04-10,13.1707
...,...,...,...,...,...
235,532067,KONOSUBA – God's blessing on this wonderful wo...,599,2019-08-30,3.0054
236,1955,The Elephant Man,3834,1980-10-09,4.1170
237,381284,Hidden Figures,10268,2016-12-10,7.1231
238,439,La Dolce Vita,2002,1960-02-05,2.7214
239,518068,Along with the Gods: The Last 49 Days,733,2018-08-01,3.7210

In [75]:
df.to_csv('movies.csv')

# NEW PROJECT API:

In [2]:
import http.client

conn = http.client.HTTPSConnection("weatherapi-com.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "261fafa0fdmshd6cb8af824e12a4p16fe70jsn4a99a76d5d52",
    'x-rapidapi-host': "weatherapi-com.p.rapidapi.com"
}

conn.request("GET", "/alerts.json?q=london", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

{"location":{"name":"London","region":"City of London, Greater London","country":"United Kingdom","lat":51.5171,"lon":-0.1062,"tz_id":"Europe/London","localtime_epoch":1771998545,"localtime":"2026-02-25 05:49"},"alerts":{"alert":[]}}

In [3]:
import json

json_data = json.loads(data.decode("utf-8"))

print(json_data)

{'location': {'name': 'London', 'region': 'City of London, Greater London', 'country': 'United Kingdom', 'lat': 51.5171, 'lon': -0.1062, 'tz_id': 'Europe/London', 'localtime_epoch': 1771998545, 'localtime': '2026-02-25 05:49'}, 'alerts': {'alert': []}}

In [7]:
import requests

url = "https://weatherapi-com.p.rapidapi.com/alerts.json"

querystring = {"q":"London"}

headers = {
    "X-RapidAPI-Key": "261fafa0fdmshd6cb8af824e12a4p16fe70jsn4a99a76d5d52",
    "X-RapidAPI-Host": "weatherapi-com.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

df = pd.DataFrame(response.json()['results'])[['id','title','vote_count','release_date','popularity']]
df.head()

London
United Kingdom

In [8]:
import http.client

conn = http.client.HTTPSConnection("weatherapi-com.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "261fafa0fdmshd6cb8af824e12a4p16fe70jsn4a99a76d5d52",
    'x-rapidapi-host': "weatherapi-com.p.rapidapi.com"
}

conn.request("GET", "/current.json?q=53.1%2C-0.13", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

{"location":{"name":"Moor Side","region":"Lincolnshire","country":"United Kingdom","lat":53.1,"lon":-0.142,"tz_id":"Europe/London","localtime_epoch":1771999013,"localtime":"2026-02-25 05:56"},"current":{"last_updated_epoch":1771998300,"last_updated":"2026-02-25 05:45","temp_c":9.1,"temp_f":48.4,"is_day":0,"condition":{"text":"Mist","icon":"//cdn.weatherapi.com/weather/64x64/night/143.png","code":1030},"wind_mph":10.5,"wind_kph":16.9,"wind_degree":167,"wind_dir":"SSE","pressure_mb":1013.0,"pressure_in":29.91,"precip_mm":0.0,"precip_in":0.0,"humidity":100,"cloud":75,"feelslike_c":6.6,"feelslike_f":43.8,"windchill_c":5.9,"windchill_f":42.7,"heatindex_c":8.6,"heatindex_f":47.5,"dewpoint_c":7.8,"dewpoint_f":46.1,"vis_km":1.3,"vis_miles":0.0,"uv":0.0,"gust_mph":20.6,"gust_kph":33.1}}

In [9]:
import json

json_data = json.loads(data.decode("utf-8"))

print(json_data)

{'location': {'name': 'Moor Side', 'region': 'Lincolnshire', 'country': 'United Kingdom', 'lat': 53.1, 'lon': -0.142, 'tz_id': 'Europe/London', 'localtime_epoch': 1771999013, 'localtime': '2026-02-25 05:56'}, 'current': {'last_updated_epoch': 1771998300, 'last_updated': '2026-02-25 05:45', 'temp_c': 9.1, 'temp_f': 48.4, 'is_day': 0, 'condition': {'text': 'Mist', 'icon': '//cdn.weatherapi.com/weather/64x64/night/143.png', 'code': 1030}, 'wind_mph': 10.5, 'wind_kph': 16.9, 'wind_degree': 167, 'wind_dir': 'SSE', 'pressure_mb': 1013.0, 'pressure_in': 29.91, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 100, 'cloud': 75, 'feelslike_c': 6.6, 'feelslike_f': 43.8, 'windchill_c': 5.9, 'windchill_f': 42.7, 'heatindex_c': 8.6, 'heatindex_f': 47.5, 'dewpoint_c': 7.8, 'dewpoint_f': 46.1, 'vis_km': 1.3, 'vis_miles': 0.0, 'uv': 0.0, 'gust_mph': 20.6, 'gust_kph': 33.1}}

In [11]:
import http.client
import json

conn = http.client.HTTPSConnection("weatherapi-com.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "261fafa0fdmshd6cb8af824e12a4p16fe70jsn4a99a76d5d52",
    'x-rapidapi-host': "weatherapi-com.p.rapidapi.com"
}

conn.request("GET", "/current.json?q=53.1%2C-0.13", headers=headers)

res = conn.getresponse()
data = res.read()

weather = json.loads(data.decode("utf-8"))

print("City:", weather["location"]["name"])
print("Country:", weather["location"]["country"])
print("Temperature:", weather["current"]["temp_c"], "°C")
print("Condition:", weather["current"]["condition"]["text"])
print("Humidity:", weather["current"]["humidity"], "%")
print("Wind Speed:", weather["current"]["wind_kph"], "kph")

City: Moor Side
Country: United Kingdom
Temperature: 9.1 °C
Condition: Mist
Humidity: 100 %
Wind Speed: 16.9 kph